version: "3"

services:
  webapi:
    image: webapiacr.azurecr.io/web_api
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
  db:
    image: microsoft/mssql-server-linux
    hostname: 'db'
    ports:
      - "9001:1433"
    environment:
      DatabaseServer: "db"
      DatabaseUser: "SA"
      SA_PASSWORD: "Secret777"
      ACCEPT_EULA: "Y"