version: "3"

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux # test for mssql-2019
    hostname: 'db'
    ports:
      - "9001:1433"
    environment:
      DatabaseServer: "db"
      DatabaseUser: "SA"
      SA_PASSWORD: "Secret777"
      ACCEPT_EULA: "Y"